version: 2.1

jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run test
  deployBackend:
    machine: true
    steps:
      - run: echo "Backend deployed"
  integrationTestsBackend:
    machine: true
    steps:
      - run: echo "Backend tests....OK"
  deployStaging:
    machine: true
    steps:
      - run: echo "Staging deployed"
  acceptanceTest1:
    machine: true
    steps:
      - run: echo "tests 1 have passed!"
  acceptanceTest2:
    machine: true
    steps:
      - run: echo "tests 2 have passed!"
  acceptanceTest3:
    machine: true
    steps:
      - run: echo "tests 3 have passed!"
  acceptanceTest4:
    machine: true
    steps:
      - run: echo "tests 4 have passed!"
  deployProduction:
    machine: true
    steps:
      - run: echo "Production deployed"
workflows:
  build:
    jobs:
      - checkoutAndTest                                 
      - deployBackend:
          requires:
            - checkoutAndTest
      - integrationTestsBackend:
          requires:
            - deployBackend
      - deployStaging:
          requires:
            - integrationTestsBackend
      - acceptanceTest1
      - acceptanceTest2
      - acceptanceTest3
      - acceptanceTest4
      - deployProduction:
        requires:
          - acceptanceTest1
          - acceptanceTest2
          - acceptanceTest3
          - acceptanceTest4